### ISSUE TITLE
Can't choose file for sending

### ISSUE THREAD

**Issue by smarnv** [pavelsof/mobile-wormhole#2]
I can't send anything. Tried with different types of files (text and images), including files I just received with the app, but it didn't help. I already gave permission to access files on the device.

When I attempt to send a file, the screen with the code appears in the app. I try to choose the file I want to send, but then it doesn't show as chosen and when I click on the `Send` button I get the error message: **"Please choose a file to send."**

Version: 0.1.4
Can reproduce on Android 7 and Android 9.

**Comment by pavelsof** [comment]
Hopefully this is fixed with the new version (0.2.0) :slightly_smiling_face:

**Comment by chymian** [comment]
unfortunalely it's not fixed in 0.2.1
independent whether I try to choose a file from the app, or share a file from i.e. filemanager, WH does not accept it.

regarding receiving: in the  **very small** input field one cannot paste. the pop-up does not work - closes on finger-release, so that one cannot choose <paste>

OS: linege OS 14.1 / aka android 7.1.2
app installed from fdroid.
